import java.time.LocalTime;
import java.util.List;

public final class IndirectTrip extends Trip {

    private final LayoverPolicy policy;

    /**
     * Creates an IndirectTrip with a specific layover policy.
     * The trip's ID is automatically generated by summing the numeric parts
     * of its constituent Route IDs (e.g., R13 + R1569 + R1621 = "3203").
     * The trip's connections are validated against this policy upon creation.
     *
     * @param legs   The list of 2 or 3 routes.
     * @param policy The policy to check layovers against.
     * @throws IllegalArgumentException if legs are invalid, layovers violate the policy,
     * or route IDs are in an invalid format for ID generation.
     */
    public IndirectTrip(List<Route> legs, LayoverPolicy policy) {
        super(generateId(legs), legs);

        if (legs.size() < 2 || legs.size() > 3) {
            throw new IllegalArgumentException("IndirectTrip must have 2 or 3 legs.");
        }
        if (policy == null) {
            throw new IllegalArgumentException("LayoverPolicy must not be null.");
        }
        this.policy = policy;

        if (!areLayoversAcceptable()) {
            throw new IllegalArgumentException("Trip " + getId() + " violates layover policy.");
        }
    }



    /**
     * Generates the IndirectTrip ID by summing the numeric parts of the Route IDs.
     * Example: "R00013" + "R01569" + "R01621" becomes 13 + 1569 + 1621 = "3203"
     *
     * @param legs The list of routes for this trip.
     * @return A String representation of the summed IDs.
     */
    private static String generateId(List<Route> legs) {
        if (legs == null || legs.isEmpty()) {
            throw new IllegalArgumentException("Cannot generate ID from null or empty legs list.");
        }

        int totalId = 0;

        for (Route r : legs) {
            try {
                String routeId = r.getId(); 
                
                totalId += Integer.parseInt(routeId.substring(1));
                
            } catch (NumberFormatException e) {
                throw new IllegalArgumentException("Invalid Route ID format: " + r.getId(), e);
                
            } catch (Exception e) {
                throw new IllegalArgumentException("Error processing route ID during generation.", e);
            
            }
        }
        

        return String.valueOf("R"+totalId);
    }

    
    private boolean areLayoversAcceptable() {
        for (int i = 0; i < getLegs().size() - 1; i++) {

            Route first = getLegs().get(i);
            Route next = getLegs().get(i + 1);

            LocalTime arr = first.getArrivalTime();
            LocalTime dep = next.getDepartureTime();

            if (!policy.isLayoverAllowed(arr, dep)) {
                return false;
            }
        }

        return true;
    }


    public LayoverPolicy getPolicy() {
        return policy;
    }
}